[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
fs_permissions = [{ access = "read-write", path = "./deployments" }, { access = "read-write", path = ".forge-snapshots/"}]
solc_version = "0.8.26"
evm_version = "cancun"
viaIR = true
optimizer = true
optimizer_runs = 200

# Add RPC URL configuration
[rpc_endpoints]
sepolia = "${RPC_URL_SEPOLIA}"
mainnet = "${RPC_URL_MAINNET}"
base = "${RPC_URL_BASE}"
arbitrum = "${RPC_URL_ARBITRUM}" # Added Arbitrum One

[profile.ci]
verbosity = 4

[fmt]
line_length = 100
number_underscore = "thousands"

# Add etherscan API key configuration
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }